import type { Coord, Journey } from "@living-journeys/engine";
import napoleon from "../journeys/napoleon-1812/bundle.json";
import oregon from "../journeys/oregon-trail-1843/bundle.json";
import shackleton from "../journeys/shackleton-1914/bundle.json";
import silkRoad from "../journeys/silk-road-1300/bundle.json";

/**
 * App-facing content: each journey's manifest plus its resolved route coordinates,
 * ready to hand to the engine's `loadJourney`. Generated by `pnpm content:build`.
 */
export type JourneyBundle = {
  manifest: Journey;
  routeCoords: Record<string, Coord[]>;
};

const bundles = [napoleon, oregon, shackleton, silkRoad] as unknown as JourneyBundle[];

export const journeyBundles: Record<string, JourneyBundle> = Object.fromEntries(
  bundles.map((b) => [b.manifest.id, b]),
);

export type JourneySummary = {
  slug: string;
  title: string;
  description?: string;
  tier: "free" | "premium";
};

export const journeyList: JourneySummary[] = bundles.map((b) => ({
  slug: b.manifest.id,
  title: b.manifest.title,
  description: b.manifest.description,
  tier: b.manifest.tier,
}));

export function getJourneyBundle(slug: string): JourneyBundle | undefined {
  return journeyBundles[slug];
}
